# Generated by Django 5.2.8 on 2025-12-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
